version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "reportA2AFraudDetection"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cwepqicuf31o"
s3_prefix = "reportA2AFraudDetection"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"

