version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "allied-SendEmail"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-16vmd993fifjh"
s3_prefix = "allied-SendEmail"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

